/**
 * Auto-generated file: Copy sections from FLASH to RAM before main()
 * This file is generated by BufferFlowX section management system.
 */

#include <string.h>

// Function declarations for copying sections
extern char _start_component1_data[];
extern char _end_component1_data[];
// For LMA (Load Memory Address), we use the symbol provided by the linker script
extern char __load_start_component1_data[];


// Copy function implementation
static void bfx_copy_sections_to_ram(void) {
    // Copy .component1.data from FLASH to RAM
    memcpy(_start_component1_data, __load_start_component1_data, 
           _end_component1_data - _start_component1_data);
}

// Constructor function that runs before main()
__attribute__((constructor)) void bfx_init_sections(void) {
    bfx_copy_sections_to_ram();
}